"""Deterministic, market-driven focus selection for Market and Tech reports.

The focus sections are a system-generated market attention list, not a user
watchlist.  Selection is sector-first and stock-second:

1. take the report's PIT active SW L2 sectors;
2. rank their members with observable price, liquidity, order-flow and formal
   leader-role evidence;
3. split the ranked result into an action-oriented important tier and a lower
   conviction tracking tier.

LLMs never choose, add or reorder tickers.  The report run persists the audit
payload alongside the selected rows, so a historical report remains
explainable even when the next run produces a different list.

Slot semantics are deliberately asymmetric:

* morning: previous closed trading-day features;
* noon: strictly prior-day features plus today's realtime quote overlay;
* evening: today's closed features, with realtime overlay only when the local
  EOD pipeline has not finished yet.

There is no hard-coded ticker fallback.  If a source is unavailable we either
select from the remaining dynamic sources or return a visibly degraded/empty
selection.
"""
from __future__ import annotations

import datetime as dt
import math
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping, Sequence

import pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import Engine

from ifa.core.report.timezones import BJT
from ifa.core.tushare import TuShareClient


LOGIC_VERSION = "dynamic_focus_v1_0"


@dataclass(frozen=True)
class FocusStock:
    """Stable report-facing focus-stock contract.

    ``note`` carries the deterministic selection explanation.  It is evidence
    for the narrative layer; it is never generated by the LLM.
    """

    ts_code: str
    display_name: str
    layer: str
    sub_theme: str
    note: str = ""


@dataclass
class FocusSelection:
    important: list[FocusStock]
    regular: list[FocusStock]
    audit: dict[str, Any]


@dataclass
class _Candidate:
    ts_code: str
    name: str = ""
    sector_code: str = ""
    sector_name: str = ""
    layer: str = "market"
    role: str = ""
    formal_score: float | None = None
    pct_change: float | None = None
    amount_yuan: float | None = None
    turnover_rate: float | None = None
    volume_ratio: float | None = None
    main_net_yuan: float | None = None
    main_net_ratio: float | None = None
    sector_state: str = ""
    sector_state_score: float | None = None
    sector_confidence: float | None = None
    sector_main_net_ratio: float | None = None
    diffusion_score: float | None = None
    quality_flag: str = ""
    risk_flags: list[str] = field(default_factory=list)
    source_tags: set[str] = field(default_factory=set)
    score: float = 0.0
    confirmations: int = 0
    selection_state: str = "tracking"
    reason: str = ""


_ROLE_SCORE = {
    "龙头": 1.00,
    "情绪先锋": 0.92,
    "中军": 0.84,
    "趋势": 0.72,
    "补涨": 0.58,
    "limit_up": 1.00,
    "breakout": 0.82,
    "mid": 0.55,
}

_STATE_LABEL = {
    "leader_confirmed": "核心确认",
    "breakout_confirmed": "突破确认",
    "rotation_confirmed": "轮动确认",
    "risk_watch": "风险观察",
    "tracking": "持续跟踪",
}


def select_market_focus(
    *,
    engine: Engine,
    client: TuShareClient,
    on_date: dt.date,
    slot: str,
    main_lines: Sequence[Any] = (),
    fund_top: Sequence[Any] = (),
    dragon_tiger: Sequence[Any] = (),
    important_limit: int = 10,
    regular_limit: int = 20,
) -> FocusSelection:
    """Select the Main report's dynamic market focus list."""

    is_live_date = on_date == dt.datetime.now(BJT).date()
    # A historical noon report has no persisted intraday SW snapshot.  Its
    # upstream ``main_lines`` call may therefore resolve to the later EOD row;
    # ignore it rather than leak the close into an intraday replay.
    active = [] if slot == "noon" and not is_live_date else _active_sectors_from_bars(main_lines)
    candidates, base_date, load_notes = _load_member_candidates(
        engine,
        on_date=on_date,
        slot=slot,
        active_sector_codes=[x[0] for x in active],
    )
    if slot == "noon" and not is_live_date:
        load_notes.append("historical_no_intraday_replay")

    # When the main-line source is unavailable, sector-state data still gives
    # us a PIT dynamic universe.  It is not a fixed thematic substitute.
    if not active:
        active = _active_sectors_from_candidates(candidates, limit=10)

    _merge_market_event_sources(candidates, fund_top=fund_top, dragon_tiger=dragon_tiger)
    _apply_quote_overlay(
        candidates,
        client=client,
        on_date=on_date,
        slot=slot,
        allow_realtime=slot in {"noon", "evening"},
    )
    _resolve_names(client, candidates, on_date=on_date)

    return _rank_and_split(
        candidates,
        scope="market",
        on_date=on_date,
        slot=slot,
        base_date=base_date,
        active_sectors=active,
        important_limit=important_limit,
        regular_limit=regular_limit,
        load_notes=load_notes,
    )


def select_tech_focus(
    *,
    engine: Engine,
    client: TuShareClient,
    on_date: dt.date,
    slot: str,
    boards_by_layer: Mapping[str, Sequence[Any]],
    tech_members: Mapping[str, set[str]],
    limit_up: Sequence[Any],
    top_movers: Sequence[Any],
    moneyflow_by_code: Mapping[str, float | None],
    important_limit: int = 5,
    regular_limit: int = 10,
) -> FocusSelection:
    """Select the Tech report's dynamic five-layer focus list."""

    from ifa.families.tech.universe import sector_name, sector_to_layer

    active = _active_tech_sectors(boards_by_layer)
    all_codes = list(tech_members.keys())
    candidates, base_date, load_notes = _load_member_candidates(
        engine,
        on_date=on_date,
        slot=slot,
        # Tech scope is structurally fixed at the five-layer sector taxonomy,
        # while the stock list and active-sector ordering are fully dynamic.
        active_sector_codes=all_codes,
    )
    layer_lookup = sector_to_layer()
    for candidate in candidates.values():
        candidate.layer = layer_lookup.get(candidate.sector_code, candidate.layer)
        if not candidate.sector_name:
            candidate.sector_name = sector_name(candidate.sector_code)

    _merge_tech_event_sources(
        candidates,
        tech_members=tech_members,
        limit_up=limit_up,
        top_movers=top_movers,
        moneyflow_by_code=moneyflow_by_code,
        layer_lookup=layer_lookup,
    )
    if not active:
        active = _active_sectors_from_candidates(candidates, limit=8)
    _apply_quote_overlay(
        candidates,
        client=client,
        on_date=on_date,
        slot=slot,
        allow_realtime=slot == "evening",
    )
    _resolve_names(client, candidates, on_date=on_date)

    return _rank_and_split(
        candidates,
        scope="tech",
        on_date=on_date,
        slot=slot,
        base_date=base_date,
        active_sectors=active,
        important_limit=important_limit,
        regular_limit=regular_limit,
        load_notes=load_notes,
    )


def _load_member_candidates(
    engine: Engine,
    *,
    on_date: dt.date,
    slot: str,
    active_sector_codes: list[str],
) -> tuple[dict[str, _Candidate], dt.date | None, list[str]]:
    """Load PIT member-stock evidence without crossing the report cutoff."""

    notes: list[str] = []
    strict_prior = slot == "noon"
    cmp = "<" if strict_prior else "<="
    try:
        with engine.connect() as conn:
            base_date = conn.execute(
                text(
                    "SELECT MAX(trade_date) FROM sme.sme_stock_orderflow_daily "
                    f"WHERE trade_date {cmp} :on_date"
                ),
                {"on_date": on_date},
            ).scalar()
            snapshot_month = conn.execute(
                text(
                    "SELECT MAX(snapshot_month) FROM smartmoney.sw_member_monthly "
                    "WHERE snapshot_month <= :month"
                ),
                {"month": on_date.replace(day=1)},
            ).scalar()
    except Exception as exc:  # SQLite/unit-test or temporarily unavailable DB
        return {}, None, [f"db_unavailable:{type(exc).__name__}"]

    if base_date is None:
        notes.append("missing_stock_feature_date")
    if snapshot_month is None:
        return {}, base_date, notes + ["missing_membership_snapshot"]

    sector_filter = ""
    params: dict[str, Any] = {
        "base_date": base_date,
        "snapshot_month": snapshot_month,
    }
    if active_sector_codes:
        sector_filter = "AND m.l2_code = ANY(:sector_codes)"
        params["sector_codes"] = active_sector_codes

    sql = text(
        f"""
        WITH best_signal AS (
            SELECT DISTINCT ON (ts_code)
                   ts_code, name, primary_sector_code, role, score
              FROM smartmoney.stock_signals_daily
             WHERE trade_date = :base_date
             ORDER BY ts_code, score DESC NULLS LAST
        )
        SELECT m.ts_code, m.l2_code, MAX(m.l2_name) AS l2_name,
               bs.name, bs.role, bs.score,
               so.pct_chg, so.amount_yuan, so.turnover_rate, so.volume_ratio,
               so.main_net_yuan, so.main_net_ratio, so.quality_flag,
               ss.current_state, ss.state_score, ss.state_confidence,
               ss.risk_flags_json,
               sec.main_net_ratio AS sector_main_net_ratio,
               dif.diffusion_score
          FROM smartmoney.sw_member_monthly m
          LEFT JOIN best_signal bs
            ON bs.ts_code = m.ts_code
           AND (bs.primary_sector_code = m.l2_code OR bs.primary_sector_code IS NULL)
          LEFT JOIN sme.sme_stock_orderflow_daily so
            ON so.trade_date = :base_date AND so.ts_code = m.ts_code
          LEFT JOIN sme.sme_sector_state_daily ss
            ON ss.trade_date = :base_date AND ss.l2_code = m.l2_code
          LEFT JOIN sme.sme_sector_orderflow_daily sec
            ON sec.trade_date = :base_date AND sec.l2_code = m.l2_code
          LEFT JOIN sme.sme_sector_diffusion_daily dif
            ON dif.trade_date = :base_date AND dif.l2_code = m.l2_code
         WHERE m.snapshot_month = :snapshot_month
           AND m.l2_code IS NOT NULL
           {sector_filter}
         GROUP BY m.ts_code, m.l2_code, bs.name, bs.role, bs.score,
                  so.pct_chg, so.amount_yuan, so.turnover_rate, so.volume_ratio,
                  so.main_net_yuan, so.main_net_ratio, so.quality_flag,
                  ss.current_state, ss.state_score, ss.state_confidence,
                  ss.risk_flags_json, sec.main_net_ratio, dif.diffusion_score
        """
    )
    try:
        with engine.connect() as conn:
            rows = conn.execute(sql, params).mappings().all()
    except Exception as exc:
        return {}, base_date, notes + [f"candidate_query_failed:{type(exc).__name__}"]

    out: dict[str, _Candidate] = {}
    for row in rows:
        code = str(row.get("ts_code") or "")
        if not code:
            continue
        flags = row.get("risk_flags_json")
        if not isinstance(flags, list):
            flags = []
        out[code] = _Candidate(
            ts_code=code,
            name=str(row.get("name") or ""),
            sector_code=str(row.get("l2_code") or ""),
            sector_name=str(row.get("l2_name") or row.get("l2_code") or ""),
            role=str(row.get("role") or ""),
            formal_score=_f(row.get("score")),
            pct_change=_f(row.get("pct_chg")),
            amount_yuan=_f(row.get("amount_yuan")),
            turnover_rate=_f(row.get("turnover_rate")),
            volume_ratio=_f(row.get("volume_ratio")),
            main_net_yuan=_f(row.get("main_net_yuan")),
            main_net_ratio=_f(row.get("main_net_ratio")),
            sector_state=str(row.get("current_state") or ""),
            sector_state_score=_f(row.get("state_score")),
            sector_confidence=_f(row.get("state_confidence")),
            sector_main_net_ratio=_f(row.get("sector_main_net_ratio")),
            diffusion_score=_f(row.get("diffusion_score")),
            quality_flag=str(row.get("quality_flag") or ""),
            risk_flags=[str(v) for v in flags if v],
            source_tags={"pit_membership", "eod_features"},
        )
    return out, base_date, notes


def _active_sectors_from_bars(bars: Sequence[Any]) -> list[tuple[str, str, float | None]]:
    out: list[tuple[str, str, float | None]] = []
    seen: set[str] = set()
    for bar in bars:
        code = str(getattr(bar, "code", None) or getattr(bar, "ts_code", None) or "")
        if not code or code in seen:
            continue
        seen.add(code)
        out.append((code, str(getattr(bar, "name", None) or code), _f(getattr(bar, "pct_change", None))))
    return out


def _active_tech_sectors(boards_by_layer: Mapping[str, Sequence[Any]]) -> list[tuple[str, str, float | None]]:
    rows: list[tuple[str, str, float | None]] = []
    for boards in boards_by_layer.values():
        rows.extend(_active_sectors_from_bars(boards))
    rows.sort(key=lambda x: (x[2] is not None, x[2] if x[2] is not None else -999.0), reverse=True)
    return rows[:8]


def _active_sectors_from_candidates(
    candidates: Mapping[str, _Candidate], *, limit: int
) -> list[tuple[str, str, float | None]]:
    best: dict[str, tuple[str, float]] = {}
    for candidate in candidates.values():
        if not candidate.sector_code:
            continue
        state = candidate.sector_state_score if candidate.sector_state_score is not None else 0.0
        diffusion = candidate.diffusion_score if candidate.diffusion_score is not None else 0.0
        main = _normalise_ratio(candidate.sector_main_net_ratio)
        value = state * 0.50 + diffusion * 0.30 + main * 0.20
        previous = best.get(candidate.sector_code)
        if previous is None or value > previous[1]:
            best[candidate.sector_code] = (candidate.sector_name or candidate.sector_code, value)
    ranked = sorted(best.items(), key=lambda x: x[1][1], reverse=True)[:limit]
    return [(code, name_value[0], name_value[1]) for code, name_value in ranked]


def _merge_market_event_sources(
    candidates: dict[str, _Candidate], *, fund_top: Sequence[Any], dragon_tiger: Sequence[Any]
) -> None:
    for rows, tag in ((fund_top, "fund_top"), (dragon_tiger, "dragon_tiger")):
        for row in rows:
            code = str(getattr(row, "ts_code", "") or "")
            if not code:
                continue
            candidate = candidates.get(code)
            # Event-only rows outside the active-sector universe do not enter
            # the Main focus list; the dedicated 龙虎榜 section still shows them.
            if candidate is None:
                continue
            candidate.source_tags.add(tag)
            candidate.name = candidate.name or str(getattr(row, "name", "") or "")
            candidate.pct_change = _first(_f(getattr(row, "pct_change", None)), candidate.pct_change)
            candidate.amount_yuan = _first(_f(getattr(row, "amount", None)), candidate.amount_yuan)
            event_flow = _f(getattr(row, "moneyflow_net", None))
            if event_flow is not None and candidate.main_net_yuan is None:
                candidate.main_net_yuan = event_flow


def _merge_tech_event_sources(
    candidates: dict[str, _Candidate],
    *,
    tech_members: Mapping[str, set[str]],
    limit_up: Sequence[Any],
    top_movers: Sequence[Any],
    moneyflow_by_code: Mapping[str, float | None],
    layer_lookup: Mapping[str, str],
) -> None:
    code_sector: dict[str, str] = {}
    for sector_code, members in tech_members.items():
        for code in members:
            code_sector.setdefault(code, sector_code)

    for rows, tag in ((limit_up, "limit_up"), (top_movers, "top_mover")):
        for row in rows:
            code = str(getattr(row, "ts_code", "") or "")
            if not code:
                continue
            sector_code = code_sector.get(code, "")
            candidate = candidates.setdefault(
                code,
                _Candidate(
                    ts_code=code,
                    sector_code=sector_code,
                    sector_name=sector_code,
                    layer=layer_lookup.get(sector_code, "market"),
                    source_tags={"intraday_or_daily_mover"},
                ),
            )
            candidate.source_tags.add(tag)
            candidate.name = candidate.name or str(getattr(row, "name", "") or "")
            candidate.pct_change = _first(_f(getattr(row, "pct_change", None)), candidate.pct_change)
            # Upstream daily amount may be 千元 while limit_list/rt sources can
            # use other units.  It is used only as a within-run percentile.
            candidate.amount_yuan = _first(_f(getattr(row, "amount", None)), candidate.amount_yuan)
            candidate.turnover_rate = _first(_f(getattr(row, "turnover_rate", None)), candidate.turnover_rate)
            row_role = str(getattr(row, "role", "") or "")
            if row_role and _ROLE_SCORE.get(row_role, 0) > _ROLE_SCORE.get(candidate.role, 0):
                candidate.role = row_role
            row_layer = str(getattr(row, "layer_id", "") or "")
            if row_layer:
                candidate.layer = row_layer

    for code, value in moneyflow_by_code.items():
        candidate = candidates.get(code)
        if candidate is None:
            continue
        candidate.source_tags.add("official_moneyflow")
        if candidate.main_net_yuan is None:
            candidate.main_net_yuan = _f(value)


def _apply_quote_overlay(
    candidates: dict[str, _Candidate],
    *,
    client: TuShareClient,
    on_date: dt.date,
    slot: str,
    allow_realtime: bool,
) -> None:
    is_live_date = on_date == dt.datetime.now(BJT).date()
    if allow_realtime and is_live_date:
        try:
            from ifa.families.market._sw_realtime import _load_whole_a_rt_k

            rt = _load_whole_a_rt_k(client, on_date=on_date)
        except Exception:
            rt = None
        if rt is not None and not rt.empty:
            for row in rt.itertuples():
                candidate = candidates.get(str(row.ts_code))
                if candidate is None:
                    continue
                close = _f(getattr(row, "close", None))
                pre_close = _f(getattr(row, "pre_close", None))
                if close is not None and pre_close and pre_close > 0:
                    candidate.pct_change = (close / pre_close - 1.0) * 100.0
                candidate.amount_yuan = _first(_f(getattr(row, "amount", None)), candidate.amount_yuan)
                candidate.source_tags.add("realtime_quote")
            return

    # Noon must never consume the observation day's EOD daily row.  If realtime
    # is unavailable, retain the strictly-prior feature snapshot and mark the
    # selection degraded instead of fabricating an intraday replay.
    if slot == "noon":
        return

    # EOD fallback also lets the selector operate when local feature tables lag.
    try:
        daily = client.call("daily", trade_date=on_date.strftime("%Y%m%d"))
    except Exception:
        daily = None
    if daily is None or daily.empty:
        return
    for row in daily.itertuples():
        candidate = candidates.get(str(row.ts_code))
        if candidate is None:
            continue
        candidate.pct_change = _first(_f(getattr(row, "pct_chg", None)), candidate.pct_change)
        raw_amount = _f(getattr(row, "amount", None))
        if raw_amount is not None:
            candidate.amount_yuan = raw_amount * 1000.0
        candidate.source_tags.add("official_daily")


def _resolve_names(client: TuShareClient, candidates: Mapping[str, _Candidate], *, on_date: dt.date) -> None:
    missing = [c for c in candidates.values() if not c.name]
    if not missing:
        return
    try:
        basic = client.call("stock_basic", exchange="", list_status="L")
    except Exception:
        return
    if basic is None or basic.empty:
        return
    names = {str(r.ts_code): str(r.name or "") for r in basic.itertuples()}
    for candidate in missing:
        candidate.name = names.get(candidate.ts_code, candidate.name)


def _rank_and_split(
    candidates: dict[str, _Candidate],
    *,
    scope: str,
    on_date: dt.date,
    slot: str,
    base_date: dt.date | None,
    active_sectors: list[tuple[str, str, float | None]],
    important_limit: int,
    regular_limit: int,
    load_notes: list[str],
) -> FocusSelection:
    active_rank = {code: i + 1 for i, (code, _, _) in enumerate(active_sectors)}
    active_name = {code: name for code, name, _ in active_sectors}
    active_pct = {code: pct for code, _, pct in active_sectors}

    # In Tech scope, members outside today's top active sectors remain eligible
    # for tracking, but their sector signal is deliberately weaker.
    amount_rank = _percentile_map(candidates.values(), key=lambda c: c.amount_yuan)
    formal_rank = _percentile_map(candidates.values(), key=lambda c: c.formal_score)
    flow_amount_rank = _percentile_map(candidates.values(), key=lambda c: c.main_net_yuan)

    eligible: list[_Candidate] = []
    for candidate in candidates.values():
        if candidate.sector_code in active_name:
            candidate.sector_name = active_name[candidate.sector_code]
        _score_candidate(
            candidate,
            slot=slot,
            active_rank=active_rank,
            active_pct=active_pct,
            active_count=max(len(active_sectors), 1),
            amount_percentile=amount_rank.get(candidate.ts_code, 0.0),
            formal_percentile=formal_rank.get(candidate.ts_code, 0.0),
            flow_amount_percentile=flow_amount_rank.get(candidate.ts_code, 0.0),
        )
        if _eligible(candidate, scope=scope, on_date=on_date):
            eligible.append(candidate)

    eligible.sort(key=lambda c: (c.score, c.confirmations, c.amount_yuan or 0.0, c.ts_code), reverse=True)
    important_pool = [c for c in eligible if c.score >= 0.56 and c.confirmations >= 2]
    important = _sector_aware_take(important_pool, limit=important_limit, per_sector=2, active_rank=active_rank)
    important_codes = {c.ts_code for c in important}

    regular_pool = [
        c for c in eligible
        if c.ts_code not in important_codes and c.score >= 0.43 and c.confirmations >= 1
    ]
    regular = _sector_aware_take(regular_pool, limit=regular_limit, per_sector=3, active_rank=active_rank)

    important_specs = [_to_focus_stock(c) for c in important]
    regular_specs = [_to_focus_stock(c) for c in regular]
    has_realtime = any("realtime_quote" in c.source_tags for c in important + regular)
    if not eligible:
        quality = "empty"
    elif slot == "noon" and on_date == dt.datetime.now(BJT).date() and not has_realtime:
        quality = "degraded"
        load_notes = [*load_notes, "live_noon_realtime_unavailable"]
    elif base_date is None or load_notes:
        quality = "degraded"
    else:
        quality = "ok"

    audit = {
        "logic_version": LOGIC_VERSION,
        "method": "sector_first_stock_second",
        "scope": scope,
        "slot": slot,
        "observation_date": on_date.isoformat(),
        "base_feature_date": base_date.isoformat() if base_date else None,
        "personalization": "disabled",
        "uses_hardcoded_tickers": False,
        "candidate_count": len(candidates),
        "eligible_count": len(eligible),
        "important_count": len(important_specs),
        "regular_count": len(regular_specs),
        "important_limit": important_limit,
        "regular_limit": regular_limit,
        "active_sectors": [
            {"code": code, "name": name, "rank": i + 1, "pct_change": pct}
            for i, (code, name, pct) in enumerate(active_sectors)
        ],
        "selected": {
            "important": [_audit_row(c) for c in important],
            "regular": [_audit_row(c) for c in regular],
        },
        "quality_flag": quality,
        "notes": list(dict.fromkeys(load_notes)),
    }
    return FocusSelection(important=important_specs, regular=regular_specs, audit=audit)


def _score_candidate(
    candidate: _Candidate,
    *,
    slot: str,
    active_rank: Mapping[str, int],
    active_pct: Mapping[str, float | None],
    active_count: int,
    amount_percentile: float,
    formal_percentile: float,
    flow_amount_percentile: float,
) -> None:
    rank = active_rank.get(candidate.sector_code)
    rank_signal = 0.20 if rank is None else 1.0 - (rank - 1) / max(active_count, 1) * 0.65
    state_signal = _clamp(candidate.sector_state_score, 0.0, 1.0, default=0.45)
    diffusion_signal = _clamp(candidate.diffusion_score, 0.0, 1.0, default=0.45)
    sector_pct_signal = _momentum_signal(active_pct.get(candidate.sector_code))
    sector_signal = rank_signal * 0.45 + state_signal * 0.25 + diffusion_signal * 0.15 + sector_pct_signal * 0.15

    role_signal = _ROLE_SCORE.get(candidate.role, 0.35)
    if candidate.formal_score is not None:
        role_signal = max(role_signal, formal_percentile * 0.75 + 0.20)
    if "limit_up" in candidate.source_tags:
        role_signal = 1.0

    if candidate.main_net_ratio is not None:
        flow_signal = _normalise_ratio(candidate.main_net_ratio)
    elif candidate.main_net_yuan is not None:
        flow_signal = flow_amount_percentile
    else:
        flow_signal = 0.42

    momentum_signal = _momentum_signal(candidate.pct_change)
    activity_signal = (
        amount_percentile * 0.55
        + _normalise_turnover(candidate.turnover_rate) * 0.25
        + _normalise_volume_ratio(candidate.volume_ratio) * 0.20
    )
    liquidity_signal = amount_percentile

    weights = {
        "morning": (0.28, 0.24, 0.20, 0.13, 0.10, 0.05),
        "noon": (0.24, 0.14, 0.12, 0.25, 0.13, 0.12),
        "evening": (0.25, 0.20, 0.22, 0.17, 0.10, 0.06),
    }.get(slot, (0.26, 0.20, 0.20, 0.18, 0.10, 0.06))
    score = sum(
        value * weight
        for value, weight in zip(
            (sector_signal, role_signal, flow_signal, momentum_signal, liquidity_signal, activity_signal),
            weights,
        )
    )
    if "dragon_tiger" in candidate.source_tags:
        score += 0.04
    if "fund_top" in candidate.source_tags and (candidate.main_net_yuan or 0) > 0:
        score += 0.05
    if "limit_up" in candidate.source_tags:
        score += 0.06
    if candidate.quality_flag and candidate.quality_flag != "ok":
        score -= 0.04
    if candidate.sector_state in {"distribution", "cooldown"}:
        score -= 0.10
    if candidate.main_net_ratio is not None and candidate.main_net_ratio < -0.10:
        score -= 0.08
    candidate.score = round(_clamp(score, 0.0, 1.0, default=0.0), 4)

    confirmations = 0
    if rank is not None and rank <= min(active_count, 6):
        confirmations += 1
    if role_signal >= 0.70:
        confirmations += 1
    if flow_signal >= 0.58:
        confirmations += 1
    if momentum_signal >= 0.62:
        confirmations += 1
    if amount_percentile >= 0.65:
        confirmations += 1
    if {"limit_up", "dragon_tiger", "fund_top"} & candidate.source_tags:
        confirmations += 1
    candidate.confirmations = confirmations

    if candidate.sector_state in {"distribution", "cooldown"} or (
        candidate.main_net_ratio is not None and candidate.main_net_ratio < -0.10
    ):
        candidate.selection_state = "risk_watch"
    elif "limit_up" in candidate.source_tags or (candidate.pct_change or 0) >= 5.0:
        candidate.selection_state = "breakout_confirmed"
    elif candidate.role in {"龙头", "中军", "情绪先锋"} and confirmations >= 3:
        candidate.selection_state = "leader_confirmed"
    elif rank is not None and confirmations >= 2:
        candidate.selection_state = "rotation_confirmed"
    else:
        candidate.selection_state = "tracking"
    candidate.reason = _selection_reason(candidate, sector_rank=rank)


def _eligible(candidate: _Candidate, *, scope: str, on_date: dt.date) -> bool:
    if not candidate.ts_code or not candidate.sector_code:
        return False
    if candidate.amount_yuan is not None and candidate.amount_yuan <= 0:
        return False
    # Current names are suitable for a live risk veto, but must not be applied
    # to historical replay where the current ST label would violate PIT.
    if on_date == dt.datetime.now(BJT).date() and candidate.name:
        compact = candidate.name.upper().replace(" ", "")
        if "ST" in compact or "退" in compact:
            return False
    if scope == "tech" and candidate.layer in {"", "market", "non_tech"}:
        return False
    return candidate.pct_change is not None or candidate.role != "" or bool(candidate.source_tags & {"limit_up", "top_mover"})


def _sector_aware_take(
    candidates: Sequence[_Candidate],
    *,
    limit: int,
    per_sector: int,
    active_rank: Mapping[str, int],
) -> list[_Candidate]:
    if limit <= 0:
        return []
    selected: list[_Candidate] = []
    seen: set[str] = set()
    sector_counts: dict[str, int] = {}

    # First pass represents the strongest current sectors once; second pass
    # fills by stock score.  This is an information-coverage rule, not a
    # portfolio diversification constraint.
    for sector_code, _ in sorted(active_rank.items(), key=lambda x: x[1]):
        choice = next((c for c in candidates if c.sector_code == sector_code and c.ts_code not in seen), None)
        if choice is None:
            continue
        selected.append(choice)
        seen.add(choice.ts_code)
        sector_counts[sector_code] = 1
        if len(selected) >= limit:
            return selected

    for candidate in candidates:
        if candidate.ts_code in seen:
            continue
        if sector_counts.get(candidate.sector_code, 0) >= per_sector:
            continue
        selected.append(candidate)
        seen.add(candidate.ts_code)
        sector_counts[candidate.sector_code] = sector_counts.get(candidate.sector_code, 0) + 1
        if len(selected) >= limit:
            break
    return selected


def _to_focus_stock(candidate: _Candidate) -> FocusStock:
    state = _STATE_LABEL.get(candidate.selection_state, "持续跟踪")
    parts = [candidate.sector_name or candidate.sector_code]
    if candidate.role:
        parts.append(candidate.role)
    parts.append(state)
    return FocusStock(
        ts_code=candidate.ts_code,
        display_name=candidate.name or candidate.ts_code,
        layer=candidate.layer or "market",
        sub_theme=" · ".join(parts),
        note=candidate.reason,
    )


def _selection_reason(candidate: _Candidate, *, sector_rank: int | None) -> str:
    reasons: list[str] = []
    if sector_rank is not None:
        reasons.append(f"活跃板块第{sector_rank}位")
    if candidate.role:
        reasons.append(f"角色={candidate.role}")
    if candidate.main_net_ratio is not None:
        direction = "流入" if candidate.main_net_ratio >= 0 else "流出"
        reasons.append(f"主力{direction}{abs(candidate.main_net_ratio) * 100:.1f}%")
    if candidate.pct_change is not None:
        reasons.append(f"涨跌幅{candidate.pct_change:+.2f}%")
    if "limit_up" in candidate.source_tags:
        reasons.append("涨停确认")
    if "dragon_tiger" in candidate.source_tags:
        reasons.append("龙虎榜事件")
    return "；".join(reasons[:4]) or "动态市场信号入选"


def _audit_row(candidate: _Candidate) -> dict[str, Any]:
    return {
        "ts_code": candidate.ts_code,
        "name": candidate.name or candidate.ts_code,
        "sector_code": candidate.sector_code,
        "sector_name": candidate.sector_name,
        "score": candidate.score,
        "confirmations": candidate.confirmations,
        "state": candidate.selection_state,
        "reason": candidate.reason,
        "sources": sorted(candidate.source_tags),
    }


def _percentile_map(
    candidates: Iterable[_Candidate], *, key
) -> dict[str, float]:
    valid: list[tuple[str, float]] = []
    for candidate in candidates:
        value = _f(key(candidate))
        if value is not None:
            valid.append((candidate.ts_code, value))
    if not valid:
        return {}
    valid.sort(key=lambda x: x[1])
    if len(valid) == 1:
        return {valid[0][0]: 1.0}
    return {code: idx / (len(valid) - 1) for idx, (code, _) in enumerate(valid)}


def _momentum_signal(pct: float | None) -> float:
    if pct is None:
        return 0.40
    points = [(-10.0, 0.05), (-3.0, 0.22), (0.0, 0.42), (3.0, 0.78), (7.0, 1.0), (12.0, 0.90), (25.0, 0.75)]
    if pct <= points[0][0]:
        return points[0][1]
    if pct >= points[-1][0]:
        return points[-1][1]
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        if x0 <= pct <= x1:
            ratio = (pct - x0) / (x1 - x0)
            return y0 + (y1 - y0) * ratio
    return 0.40


def _normalise_ratio(value: float | None) -> float:
    if value is None:
        return 0.45
    return _clamp((value + 0.10) / 0.20, 0.0, 1.0, default=0.45)


def _normalise_turnover(value: float | None) -> float:
    if value is None:
        return 0.40
    return _clamp(value / 12.0, 0.0, 1.0, default=0.40)


def _normalise_volume_ratio(value: float | None) -> float:
    if value is None:
        return 0.40
    return _clamp((value - 0.5) / 2.0, 0.0, 1.0, default=0.40)


def _clamp(value: float | None, lo: float, hi: float, *, default: float) -> float:
    if value is None or not math.isfinite(value):
        return default
    return max(lo, min(hi, value))


def _f(value: Any) -> float | None:
    try:
        if value is None or pd.isna(value):
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _first(first: float | None, second: float | None) -> float | None:
    return first if first is not None else second
